# Site-Wide Configuration

title: Adam Rodger | Blog
description: Homepage and technology blog of Adam Rodger
baseurl: ""
url: "http://adamrodger.github.io"
locale: en-GB
timezone: Europe/London

# Personal Info
twitter_username: adamrodger
github_username:  adamrodger
twitter:
  username: adamrodger
social:
  type: Person
  name: Adam Rodger
  links:
    - "https://github.com/adamrodger"
    - "https://twitter.com/adamrodger"
    - "https://www.linkedin.com/in/adamrodger/"
author:
  name          : Adam Rodger
  avatar        : "/assets/images/bio-photo.jpg"
  bio           : "Lead Developer at dunnhumby specialising in API development in .Net Core"
  uri           : "http://adamrodger.github.io"
  location      : Manchester, United Kingdom
  twitter       : adamrodger
  linkedin      : adamrodger
  github        : adamrodger
  stackoverflow : 429541/adam-rodger

# Build settings
repository: "adamrodger/adamrodger.github.com"
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast"
search: true
read_time: true
paginate: 10
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

include:
  - _pages
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  # Blog posts
  - scope:
      path: _posts
      type: posts
    values:
      layout: single
      categories: blog
      read_time: true
      share: true
      related: true
      author_profile: true
  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: page