baseURL = "https://adamrodger.com"
title = "Adam Rodger"
languageCode = "en"
enableInlineShortcodes = true
theme = "soho"

#summarylength = 10
#enableEmoji = true

[params]
author = "Adam Rodger"
description = "Blog"

## Set one of:
profilePicture = "images/profile.jpg"

copyright = "Adam Rodger"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
themeColor = "#4e5964"

## Set custom CSS and/or JS to override site defaults.
customCss = ["css/blog.css"]
#customJs = ["js/blog.js"]

  ## Set as many as you want.
  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/adamrodger/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/adamrodger"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/adamrodger"

  [[params.socialIcons]]
  icon = "fa-stack-overflow"
  title = "StackOverflow"
  url = "https://stackoverflow.com/users/429541/adam-rodger"

# [menu]

#   [[menu.main]]
#   name = "Posts"
#   weight = 100
#   identifier = "posts"
#   url = "/posts/"

#   [[menu.main]]
#   name = "About"
#   identifier = "about"
#   weight = 300
#   url = "/about/"

# [taxonomies]
#   category = "categories"
#   series = "series"
#   tag = "tags"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "dracula"
  tabWidth = 4